grails-app/domain/kyrsachv1/Malfunction.groovy
package kyrsachv1

class Malfunction {
	
	Date dateCreated
	String description
	Boolean fixed
	Date fixed_at

    static constraints = {
		description blank: false
		fixed nullable: true
		fixed_at nullable: true, blank: true
    }
	
	static belongsTo = [car: Car]
	
}

grails-app/domain/kyrsachv1/RepairJob.groovy
package kyrsachv1

class RepairJob {
	
	String description
	String price
	Boolean finished
	Date finished_at
	
	static belongsTo = [car: Car, malfunction: Malfunction, workcategory: WorkCategory]
	
    static constraints = {
		finished_at nullable: true, blank: true
    }
}

grails-app/controllers/kyrsachv1/RepairJobController.groovy
package kyrsachv1

import org.springframework.dao.DataIntegrityViolationException


@Mixin(AuthService)
class RepairJobController {

    static allowedMethods = [create: ['GET', 'POST'], edit: ['GET', 'POST'], delete: 'POST']
	
	def beforeInterceptor = [action: this.&auth]

    def index() {
        redirect action: 'list', params: params
    }

    def list() {
        params.max = Math.min(params.max ? params.int('max') : 10, 100)
        [repairJobInstanceList: RepairJob.list(params), repairJobInstanceTotal: RepairJob.count()]
    }

    def create() {
		switch (request.method) {
		case 'GET':
        	[repairJobInstance: new RepairJob(params)]
			break
		case 'POST':
	        def repairJobInstance = new RepairJob(params)
	        if (!repairJobInstance.save(flush: true)) {
	            render view: 'create', model: [repairJobInstance: repairJobInstance]
	            return
	        }

			flash.message = message(code: 'default.created.message', args: [message(code: 'repairJob.label', default: 'RepairJob'), repairJobInstance.id])
	        redirect action: 'show', id: repairJobInstance.id
			break
		}
    }

    def show() {
        def repairJobInstance = RepairJob.get(params.id)
        if (!repairJobInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'repairJob.label', default: 'RepairJob'), params.id])
            redirect action: 'list'
            return
        }

        [repairJobInstance: repairJobInstance]
    }

    def edit() {
		switch (request.method) {
		case 'GET':
	        def repairJobInstance = RepairJob.get(params.id)
	        if (!repairJobInstance) {
	            flash.message = message(code: 'default.not.found.message', args: [message(code: 'repairJob.label', default: 'RepairJob'), params.id])
	            redirect action: 'list'
	            return
	        }

	        [repairJobInstance: repairJobInstance]
			break
		case 'POST':
	        def repairJobInstance = RepairJob.get(params.id)
	        if (!repairJobInstance) {
	            flash.message = message(code: 'default.not.found.message', args: [message(code: 'repairJob.label', default: 'RepairJob'), params.id])
	            redirect action: 'list'
	            return
	        }

	        if (params.version) {
	            def version = params.version.toLong()
	            if (repairJobInstance.version > version) {
	                repairJobInstance.errors.rejectValue('version', 'default.optimistic.locking.failure',
	                          [message(code: 'repairJob.label', default: 'RepairJob')] as Object[],
	                          "Another user has updated this RepairJob while you were editing")
	                render view: 'edit', model: [repairJobInstance: repairJobInstance]
	                return
	            }
	        }

	        repairJobInstance.properties = params

	        if (!repairJobInstance.save(flush: true)) {
	            render view: 'edit', model: [repairJobInstance: repairJobInstance]
	            return
	        }

			flash.message = message(code: 'default.updated.message', args: [message(code: 'repairJob.label', default: 'RepairJob'), repairJobInstance.id])
	        redirect action: 'show', id: repairJobInstance.id
			break
		}
    }

    def delete() {
        def repairJobInstance = RepairJob.get(params.id)
        if (!repairJobInstance) {
			flash.message = message(code: 'default.not.found.message', args: [message(code: 'repairJob.label', default: 'RepairJob'), params.id])
            redirect action: 'list'
            return
        }

        try {
            repairJobInstance.delete(flush: true)
			flash.message = message(code: 'default.deleted.message', args: [message(code: 'repairJob.label', default: 'RepairJob'), params.id])
            redirect action: 'list'
        }
        catch (DataIntegrityViolationException e) {
			flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'repairJob.label', default: 'RepairJob'), params.id])
            redirect action: 'show', id: params.id
        }
    }
}

grails-app/views/repairJob/_form.gsp
<%@ page import="kyrsachv1.RepairJob" %>



<div class="fieldcontain ${hasErrors(bean: repairJobInstance, field: 'car', 'error')} required">
	<label for="car">
		<g:message code="repairJob.car.label" default="Car" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="car" name="car.id" from="${kyrsachv1.Car.list()}" optionKey="id" required="" value="${repairJobInstance?.car?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: repairJobInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="repairJob.description.label" default="Description" />
		
	</label>
	<g:textField name="description" value="${repairJobInstance?.description}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: repairJobInstance, field: 'finished', 'error')} ">
	<label for="finished">
		<g:message code="repairJob.finished.label" default="Finished" />
		
	</label>
	<g:checkBox name="finished" value="${repairJobInstance?.finished}" />
</div>

<div class="fieldcontain ${hasErrors(bean: repairJobInstance, field: 'finished_at', 'error')} required">
	<label for="finished_at">
		<g:message code="repairJob.finished_at.label" default="Finishedat" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="finished_at" precision="day"  value="${repairJobInstance?.finished_at}"  />
</div>

<div class="fieldcontain ${hasErrors(bean: repairJobInstance, field: 'malfunction', 'error')} required">
	<label for="malfunction">
		<g:message code="repairJob.malfunction.label" default="Malfunction" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="malfunction" name="malfunction.id" from="${kyrsachv1.Malfunction.list()}" optionKey="id" required="" value="${repairJobInstance?.malfunction?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: repairJobInstance, field: 'price', 'error')} ">
	<label for="price">
		<g:message code="repairJob.price.label" default="Price" />
		
	</label>
	<g:textField name="price" value="${repairJobInstance?.price}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: repairJobInstance, field: 'workcategory', 'error')} required">
	<label for="workcategory">
		<g:message code="repairJob.workcategory.label" default="Workcategory" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="workcategory" name="workcategory.id" from="${kyrsachv1.WorkCategory.list()}" optionKey="id" required="" value="${repairJobInstance?.workcategory?.id}" class="many-to-one"/>
</div>

grails-app/views/repairJob/create.gsp
<%@ page import="kyrsachv1.RepairJob" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'repairJob.label', default: 'RepairJob')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span3">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">${entityName}</li>
						<li>
							<g:link class="list" action="list">
								<i class="icon-list"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link>
						</li>
					</ul>
				</div>
			</div>
			
			<div class="span9">

				<div class="page-header">
					<h1><g:message code="default.create.label" args="[entityName]" /></h1>
				</div>

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>

				<g:hasErrors bean="${repairJobInstance}">
				<bootstrap:alert class="alert-error">
				<ul>
					<g:eachError bean="${repairJobInstance}" var="error">
					<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
					</g:eachError>
				</ul>
				</bootstrap:alert>
				</g:hasErrors>

				<fieldset>
					<g:form class="form-horizontal" action="create" >
						<fieldset>
<%--							<f:all bean="repairJobInstance"/>--%>
							<f:with bean="repairJobInstance">
								<div class="row-fluid">
									<div class="span5">
										<f:field property="car" input-optionValue="identifier" />
										<f:field property="malfunction">
											<g:select id="malfunction" name="malfunction.id" from="${repairJobInstance.car.malfunctions}" optionKey="id" optionValue="${{it.description}}" required="" value="${malfunctionInstance?.car?.brand}" class="many-to-one"/>
										</f:field>
										<f:field property="workcategory" input-optionValue="name"/>
										<br/>
										<f:field property="finished" />
										<f:field property="finished_at" />
										<f:field property="price" />
									</div>
									
									<div class="span4">
										<f:field property="description">
											<g:textArea name="description" value="${value}" rows="6" style="width:250px"/>
										</f:field>
									</div>
								</div>								
							</f:with>
							<div class="form-actions">
								<button type="submit" class="btn btn-primary">
									<i class="icon-ok icon-white"></i>
									<g:message code="default.button.create.label" default="Create" />
								</button>
							</div>
						</fieldset>
					</g:form>
				</fieldset>
				
			</div>

		</div>
	</body>
</html>

grails-app/views/repairJob/edit.gsp
<%@ page import="kyrsachv1.RepairJob" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'repairJob.label', default: 'RepairJob')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">

			<div class="span3">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">${entityName}</li>
						<li>
							<g:link class="list" action="list">
								<i class="icon-list"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link>
						</li>
					</ul>
				</div>
			</div>
			
			<div class="span9">

				<div class="page-header">
					<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
				</div>

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>

				<g:hasErrors bean="${repairJobInstance}">
				<bootstrap:alert class="alert-error">
				<ul>
					<g:eachError bean="${repairJobInstance}" var="error">
					<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
					</g:eachError>
				</ul>
				</bootstrap:alert>
				</g:hasErrors>

				<fieldset>
					<g:form class="form-horizontal" action="edit" id="${repairJobInstance?.id}" >
						<g:hiddenField name="version" value="${repairJobInstance?.version}" />
						<fieldset>
<%--							<f:all bean="repairJobInstance"/>--%>
							<f:with bean="repairJobInstance">
								<div class="row-fluid">
									<div class="span5">
										<f:field property="car" input-optionValue="identifier" />
										<f:field property="malfunction">
											<g:select id="malfunction" name="malfunction.id" from="${repairJobInstance.car.malfunctions}" optionKey="id" optionValue="${{it.description}}" required="" value="${malfunctionInstance?.car?.brand}" class="many-to-one"/>
										</f:field>
										<f:field property="workcategory" input-optionValue="name"/>
										<br/>
										<f:field property="finished" />
										<f:field property="finished_at" />
										<f:field property="price" />
									</div>
									
									<div class="span4">
										<f:field property="description">
											<g:textArea name="description" value="${value}" rows="6" style="width:250px"/>
										</f:field>
									</div>
								</div>								
							</f:with>
							<div class="form-actions">
								<button type="submit" class="btn btn-primary">
									<i class="icon-ok icon-white"></i>
									<g:message code="default.button.update.label" default="Update" />
								</button>
								<button type="submit" class="btn btn-danger" name="_action_delete" formnovalidate>
									<i class="icon-trash icon-white"></i>
									<g:message code="default.button.delete.label" default="Delete" />
								</button>
							</div>
						</fieldset>
					</g:form>
				</fieldset>

			</div>

		</div>
	</body>
</html>

grails-app/views/repairJob/list.gsp
<%@ page import="kyrsachv1.RepairJob" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'repairJob.label', default: 'RepairJob')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span3">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">${entityName}</li>
						<li class="active">
							<g:link class="list" action="list">
								<i class="icon-list icon-white"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link>
						</li>
<%--						<li>--%>
<%--							<g:link class="create" action="create">--%>
<%--								<i class="icon-plus"></i>--%>
<%--								<g:message code="default.create.label" args="[entityName]" />--%>
<%--							</g:link>--%>
<%--						</li>--%>
					</ul>
				</div>
			</div>

			<div class="span9">
				
				<div class="page-header">
					<h1><g:message code="default.list.label" args="[entityName]" /></h1>
				</div>

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>
				
				<table class="table table-striped">
					<thead>
						<tr>
						
							<th class="header">
								<g:message code="repairJob.car.label" default="Car" />
								<g:message code="repairJob.malfunction.label" default="Malfunction" />
							</th>
							
							<g:sortableColumn property="finished_at" title="${message(code: 'repairJob.workcategory.label', default: 'Work category')}" />
							
							<g:sortableColumn property="finished_at" title="${message(code: 'repairJob.finished_at.label', default: 'Completed on')}" />	
						
							<g:sortableColumn property="price" title="${message(code: 'repairJob.price.label', default: 'Price')}" />
						
							<th></th>
						</tr>
					</thead>
					<tbody>
					<g:each in="${repairJobInstanceList}" var="repairJobInstance">
						
						<g:if test="${repairJobInstance.finished}">
							<tr class="success">
						</g:if>
						<g:else>
							<tr class="error">
						</g:else>
						
							<td class="link">
								<g:link action="show" id="${repairJobInstance.id}">
									${fieldValue(bean: repairJobInstance, field: "car.identifier")}
									-
									${fieldValue(bean: repairJobInstance, field: "malfunction.description")}
								</g:link>
							</td>
							
							<td>${fieldValue(bean:repairJobInstance, field: "workcategory.name") }</td>
						
							<td><g:formatDate date="${repairJobInstance.finished_at}" /></td>							
						
							<td>${fieldValue(bean: repairJobInstance, field: "price")}</td>
						</tr>
					</g:each>
					</tbody>
				</table>
				<div class="pagination">
					<bootstrap:paginate total="${repairJobInstanceTotal}" />
				</div>
			</div>

		</div>
	</body>
</html>

grails-app/views/repairJob/show.gsp
<%@ page import="kyrsachv1.RepairJob" %>
<!doctype html>
<html>
	<head>
		<meta name="layout" content="bootstrap">
		<g:set var="entityName" value="${message(code: 'repairJob.label', default: 'RepairJob')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="row-fluid">
			
			<div class="span3">
				<div class="well">
					<ul class="nav nav-list">
						<li class="nav-header">${entityName}</li>
						<li>
							<g:link class="list" action="list">
								<i class="icon-list"></i>
								<g:message code="default.list.label" args="[entityName]" />
							</g:link>
						</li>
					</ul>
				</div>
			</div>
			
			<div class="span9">

				<div class="page-header">
					<h1><g:message code="default.show.label" args="[entityName]" /></h1>
				</div>

				<g:if test="${flash.message}">
				<bootstrap:alert class="alert-info">${flash.message}</bootstrap:alert>
				</g:if>

				<dl>
				
					<g:if test="${repairJobInstance?.car}">
						<dt><g:message code="repairJob.car.label" default="Car" /></dt>
						
							<dd><g:link controller="car" action="show" id="${repairJobInstance?.car?.id}">${repairJobInstance?.car?.encodeAsHTML()}</g:link></dd>
						
					</g:if>
				
					<g:if test="${repairJobInstance?.description}">
						<dt><g:message code="repairJob.description.label" default="Description" /></dt>
						
							<dd><g:fieldValue bean="${repairJobInstance}" field="description"/></dd>
						
					</g:if>
				
					<g:if test="${repairJobInstance?.finished}">
						<dt><g:message code="repairJob.finished.label" default="Finished" /></dt>
						
							<dd><g:formatBoolean boolean="${repairJobInstance?.finished}" /></dd>
						
					</g:if>
				
					<g:if test="${repairJobInstance?.finished_at}">
						<dt><g:message code="repairJob.finished_at.label" default="Finishedat" /></dt>
						
							<dd><g:formatDate date="${repairJobInstance?.finished_at}" /></dd>
						
					</g:if>
				
					<g:if test="${repairJobInstance?.malfunction}">
						<dt><g:message code="repairJob.malfunction.label" default="Malfunction" /></dt>
						
							<dd><g:link controller="malfunction" action="show" id="${repairJobInstance?.malfunction?.id}">${repairJobInstance?.malfunction?.encodeAsHTML()}</g:link></dd>
						
					</g:if>
				
					<g:if test="${repairJobInstance?.price}">
						<dt><g:message code="repairJob.price.label" default="Price" /></dt>
						
							<dd><g:fieldValue bean="${repairJobInstance}" field="price"/></dd>
						
					</g:if>
				
					<g:if test="${repairJobInstance?.workcategory}">
						<dt><g:message code="repairJob.workcategory.label" default="Workcategory" /></dt>
						
							<dd><g:link controller="workCategory" action="show" id="${repairJobInstance?.workcategory?.id}">${repairJobInstance?.workcategory?.encodeAsHTML()}</g:link></dd>
						
					</g:if>
				
				</dl>

				<g:form>
					<g:hiddenField name="id" value="${repairJobInstance?.id}" />
					<div class="form-actions">
						<g:link class="btn" action="edit" id="${repairJobInstance?.id}">
							<i class="icon-pencil"></i>
							<g:message code="default.button.edit.label" default="Edit" />
						</g:link>
						<button class="btn btn-danger" type="submit" name="_action_delete">
							<i class="icon-trash icon-white"></i>
							<g:message code="default.button.delete.label" default="Delete" />
						</button>
					</div>
				</g:form>

			</div>

		</div>
	</body>
</html>